from vtk import *
file_name=raw_input('File name?\n')
reader = vtkMetaImageReader()
reader.SetFileName(file_name)
reader.Update()
iso = vtkImageMarchingCubes()
iso.SetInputConnection(reader.GetOutputPort())
num = int(raw_input('How many isosurfaces do you want?.\n'))
for i in range(0,num):
  level = float(raw_input('Input the value where you want the isosurface.\n'))
  iso.SetValue(i,level)
isoMapper=vtkPolyDataMapper()
isoMapper.SetInputConnection(iso.GetOutputPort())
isoActor = vtkActor()
isoActor.SetMapper(isoMapper)
renderer = vtkRenderer()
renderer.AddActor(isoActor)
renderWindow=vtkRenderWindow()
renderWindow.AddRenderer(renderer)
renderWindowInteractor=vtkRenderWindowInteractor()
renderWindowInteractor.SetRenderWindow(renderWindow)
renderWindowInteractor.Initialize()
renderWindowInteractor.Start()
